FROM golang:alpine
ENV GO111MODULE=on

WORKDIR /app

COPY . .

RUN go mod tidy

RUN go build -v -o ./antibrutforce ./cmd/cmd.go

ENTRYPOINT ["./antibrutforce", "-config",  "./configs/test.yml"]

EXPOSE 8000