name: Otus homework tests

on:
  push:
    branches:
      - dev
      - main

env:
  GO111MODULE: "on"

jobs:
  lint:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    # if: ${{ !contains(github.ref, 'calendar') }}
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.20

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.58.1
          working-directory: ${{ github.workspace }}

  tests:
    runs-on: self-hosted
  #  if: ${{ !contains(github.ref, 'calendar') }}
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      - name: Check out code
        uses: actions/checkout@v3

      - name: Unit tests
        run: go test -timeout=90s -count=1 -v ./internal/...
        working-directory:  ${{ github.workspace }} # ${{ env.BRANCH }}

      - name: Integration tests
        run: go test -timeout=3m -count=1 -v ./tests/...
     #  if: env.BRANCH == 'dev'
        working-directory:  ${{ github.workspace }} # ${{ env.BRANCH }}

  tests_by_makefile:
    runs-on: self-hosted
#    if: contains(github.ref, 'calendar')
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      - name: Check out code
        uses: actions/checkout@v3

      - name: make lint
        run: make lint
        working-directory: ${{ github.workspace }} 

      - name: make build
        run: make build
        working-directory: ${{ github.workspace }} 

      - name: make test
        run: make test
        working-directory: ${{ github.workspace }} 